language: python

python:
  - 2.7
  - 3.5
  - 3.6

script:
  - pip install ansible
  - ansible all -i localhost, -c local -m setup -a 'filter=ansible_python'
  - ansible all -i localhost, -c local -m uri -a url=https://sh.rustup.rs/
  - python -c 'import ssl; print([a for a in dir(ssl) if a.startswith("PROTOCOL_")])'
  - python certs.py
  - sudo apt-get update
  - sudo apt-get install ca-certificates
  - sudo update-ca-certificates
  - ansible all -i localhost, -c local -m uri -a url=https://sh.rustup.rs/
  - pip install urllib3 pyopenssl cryptography idna
  - ansible all -i localhost, -c local -m uri -a url=https://sh.rustup.rs/
