language: python

python:
 - 2.7

script:
  - pip install ansible
  - ansible all -i localhost, -c local -m setup -a 'filter=ansible_python'
  - ansible all -i localhost, -c local -m uri -a url=https://sh.rustup.rs/
  - python -c 'import ssl; print([a for a in dir(ssl) if a.startswith("PROTOCOL_")])'
  - python certs.py
  - apt-get update
  - apt-get install ca-certificates
  - update-ca-certificates
