language: python

python:
 - 2.7

env:
  global:
    - secure: "Kb2Hxs5kfq3A924D4cvu6iPmeV3c7bRMrFqIIyXwtKlTtfsFnMSFCm6HrTgmSkrF/5lwWsIfKBTPismyoWYdEYijino6ZKqKITOCh7jDEhJkRb5t4E7M7BIk0yfXuqeELZhIScDPkOi+rYUBnm2IpWlq/WGWnt4bR7tF/t14oeU="

script:
 - python -V
 - python -c "import os; print os.getenv('FOO')"
 - echo $FOO
