language: python

python:
 - 2.7

env:
  global:
    - secure: "d+7KfxDSv5YX5EgBz+6Qcz7576yZeq8fep4r5CdSYNAlQDqowAV0YSHdsUea7ghOX2tffDdhQ7eHuULnp7q1QnydBf4tomYi+pS6Nx1bOBt/DMlEpx0OYeJLAOq+XQKpR2GKgZwWJAEv8l7Xo5RdTqfdrB4rWEO4N0WbSoN2uG0="

script:
 - python -V
 - python -c "import os; print os.getenv('FOO')"
 - echo $FOO
