language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

install:
  - pip install ansible

script:
  - head -1 $(which ansible)
  - ansible localhost -m setup -a 'filter=ansible_python'
  - ansible localhost -m uri -a url=https://sh.rustup.rs/
  - ansible-playbook test.yml
