language: python

python:
 - 2.7

matrix:
  include:
    - env: GOOS=linux GOARCH=amd64
    - env: GOOS=windows GOARCH=amd64
    - env: GOOS=darwin GOARCH=amd64

script:
  - go version
  - wget https://github.com/sivel/ansible/raw/ea1af4c5b4c17a349c004ca5a3dad8eb1cecf3e1/test/integration/library/helloworld.go
  - go build -o helloworld_$GOOS helloworld.go
